<<<<<<< HEAD
name: task_manager_full_sqlite
description: GestiÃ³n de tareas - Multiplataforma con SQLite (no-web) y SharedPreferences (web fallback)
=======
name: task_manager_flutter_complete
description: A Flutter migration of your Task Manager app with CRUD and offline cache
publish_to: "none"
>>>>>>> cbe15e97e9cfd517c18122b48ef1ad78029d4720
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
<<<<<<< HEAD
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.4
  sqflite_common_ffi: ^2.3.6
  shared_preferences: ^2.1.1
  bcrypt: ^1.1.3
=======
  http: ^0.13.6
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
>>>>>>> cbe15e97e9cfd517c18122b48ef1ad78029d4720

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
  flutter_lints: ^3.0.0
=======
>>>>>>> cbe15e97e9cfd517c18122b48ef1ad78029d4720

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
